
local ui = _G.AstraUI or _G.Kirin
if type(ui) ~= "table" or ui.Version ~= "4.0.0" or not ui._alive then
    warn("Load Astra UI 4.0.0 before running this example")
    return
end
ui:SetLayout("Compact")
local window = ui:CreateWindow({Title="ASTRA / MATCHA",Size={790,570},ToggleKey="h"})
local tab = window:AddTab({Title="Controls",Columns=2})
local status = tab:AddLabel("Your design, ready for other scripts. Press H to toggle the window.")
tab:AddToggle({Title="Enabled",Flag="demo.enabled",Callback=function(on)
    status:SetText(on and "Status: enabled" or "Status: disabled")
end})
tab:AddToggle({Title="Checkbox",Type="Checkbox",Flag="demo.checkbox"})
tab:AddSlider({Title="Intensity",Min=0,Max=100,Step=5,Default=30,Suffix="%",Flag="demo.amount"})
tab:AddButton({Title="Notification",Callback=function()
    ui:Notify({Title="Astra UI",Content="One click, one action.",Duration=3})
end})
tab:AddDropdown({Title="Theme",Options=ui:GetThemes(),Default="Cosmos",Flag="demo.theme",Callback=function(theme)
    ui:SetTheme(theme)
end})
tab:AddKeybind({Title="Menu key",Default="h",Callback=function(key) window:SetToggleKey(key) end})
tab:AddInput({Title="Name",Default="",Flag="demo.name",Callback=function(text) status:SetText("Hello "..text) end})
local progress=tab:AddProgressBar({Title="Progress",Default=0.4})
tab:AddColorPicker({Title="Palette",Style={Width=1},Flag="demo.color"})
local settings=window:AddTab({Title="Settings"})
settings:AddDropdown({Title="Layout",Options={"Compact","Default"},Default="Compact",Callback=function(name)
    window:SetLayout(name)
end})
settings:AddToggle({Title="Animated garden",Default=true,Callback=function(on) window:SetVisualFX(on) end})
settings:AddButton({Title="Save configuration",Callback=function()
    local ok,err=ui:SaveConfig("astra-demo.json")
    ui:Notify({Title="Configuration",Content=ok and "Saved" or tostring(err)})
end})
settings:AddButton({Title="Load configuration",Callback=function()
    local ok,err=ui:LoadConfig("astra-demo.json",false)
    ui:Notify({Title="Configuration",Content=ok and "Loaded" or tostring(err)})
end})
settings:AddButton({Title="Close UI",Style="danger",Callback=function() ui:Destroy() end})
tab:Select()
